### ISSUE TITLE
chunked transfer-encoding terminates without last-chunk

### ISSUE THREAD

**Issue by tatsuhiro-t** [nodejs/llhttp#20]
llhttp terminates chunked encoding without last-chunk ('0' + '\r\n').

For example, if I send the following request:
```
PUT / HTTP/1.1\r\nHost: localhost\r\nTransfer-Encoding: chunked\r\n\r\n1\r\nx\r\n\r\n\r\n
```

llhttp reports that request body completes.
According to RFC 7230 [1], chunked encoding requires last-chunk.

[1]: https://tools.ietf.org/html/rfc7230#section-4.1

**Comment by tatsuhiro-t** [comment]
The following patch works for me:

```patch
diff --git a/src/llhttp/http.ts b/src/llhttp/http.ts
index 622d124..5b2d769 100644
--- a/src/llhttp/http.ts
+++ b/src/llhttp/http.ts
@@ -69,6 +69,7 @@ const NODES: ReadonlyArray<string> = [
 
   'chunk_size_start',
   'chunk_size',
+  'chunk_size2',
   'chunk_size_otherwise',
   'chunk_size_almost_done',
   'chunk_size_almost_done_lf',
@@ -594,7 +595,15 @@ export class HTTP {
     n('chunk_size')
       .select(HEX_MAP, this.mulAdd('content_length', {
         overflow: p.error(ERROR.INVALID_CHUNK_SIZE, 'Chunk size overflow'),
-        success: 'chunk_size',
+        success: 'chunk_size2',
+      }, { signed: false, base: 0x10 }))
+      .otherwise(p.error(ERROR.INVALID_CHUNK_SIZE,
+        'Invalid character in chunk size'));
+
+    n('chunk_size2')
+      .select(HEX_MAP, this.mulAdd('content_length', {
+        overflow: p.error(ERROR.INVALID_CHUNK_SIZE, 'Chunk size overflow'),
+        success: 'chunk_size2',
       }, { signed: false, base: 0x10 }))
       .otherwise(n('chunk_size_otherwise'));
 
```

**Comment by indutny** [comment]
Thank you for reporting this!

The patch is very nice looking. I have a few suggestions of improvements that I'd be happy to share inline on the Pull Request. Would you be interested in submitting this patch as a PR?

Thanks again!

**Comment by tatsuhiro-t** [comment]
PR is up.  Thank you.

**Comment by iolufemi** [comment]
I also faced this issue recently.

```{ Error: Parse Error
       at TLSSocket.socketOnData (_http_client.js:442:20)
       at TLSSocket.emit (events.js:198:13)
       at TLSSocket.EventEmitter.emit (domain.js:448:20)
       at addChunk (_stream_readable.js:288:12)
       at readableAddChunk (_stream_readable.js:269:11)
       at TLSSocket.Readable.push (_stream_readable.js:224:10)
       at TLSWrap.onStreamRead (internal/stream_base_commons.js:94:17) bytesParsed: 356, code: 'HPE_INVALID_CHUNK_SIZE' }```

I noticed the server was sending the 'transfer-encoding' header twice (see image below) which was then interpreted as 'transfer-encoding': 'chunked, chunked' by the client. Couldn't get the server provider to fix it but adding a connection header fixed the issue. `Connection: 'keep-alive'`

![image](https://user-images.githubusercontent.com/4224136/67161810-1cf3fd80-f356-11e9-8c81-afb1f069ecc0.png)

**Comment by indutny** [comment]
@iolufemi this error has nothing to do with double `chunked` header. There is likely another issue in that request/response. Would you mind posting the actual request/response here or as a gist?

Thank you!
