### ISSUE TITLE
9.1.2: build fails

### ISSUE THREAD

**Issue by kloczek** [nodejs/llhttp#252]
I'm not sure what could be wrong in this case
```console
+ cd llhttp-9.1.2
+ /usr/bin/make -O -j48 V=1 VERBOSE=1 release TAG=9.1.2
rm -rf release/
rm -rf build/
npx ts-node bin/generate.ts
/home/tkloczko/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
bin/generate.ts(3,56): error TS2307: Cannot find module 'fs' or its corresponding type declarations.
bin/generate.ts(4,25): error TS2307: Cannot find module 'llparse' or its corresponding type declarations.
bin/generate.ts(5,34): error TS2307: Cannot find module 'path' or its corresponding type declarations.
bin/generate.ts(6,23): error TS2307: Cannot find module 'semver' or its corresponding type declarations.
bin/generate.ts(9,24): error TS2552: Cannot find name '__dirname'. Did you mean 'dirname'?
bin/generate.ts(10,29): error TS2552: Cannot find name '__dirname'. Did you mean 'dirname'?
bin/generate.ts(13,24): error TS2552: Cannot find name '__dirname'. Did you mean 'dirname'?
bin/generate.ts(19,44): error TS2552: Cannot find name '__dirname'. Did you mean 'dirname'?
bin/generate.ts(24,10): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

    at createTSError (/home/tkloczko/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/tkloczko/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/tkloczko/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/tkloczko/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/home/tkloczko/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.require.extensions.<computed> [as .ts] (/home/tkloczko/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
  diagnosticCodes: [
    2307, 2307, 2307,
    2307, 2552, 2552,
    2552, 2552, 2580
  ]
}
make: *** [Makefile:83: generate] Error 1
```
I'm using nodejs 20.7.0.

**Comment by ShogunPanda** [comment]
Closed as no further feedback was received. Feel free to reopen.

**Comment by kloczek** [comment]
Hmm .. what exactly needs to be done or installed? 🤔 
looking on fedora last build dependencies I don't see anything specific and they are using exactly the same version of nodejs I I;m using
https://koji.fedoraproject.org/koji/rpminfo?rpmID=38305499

**Comment by ShogunPanda** [comment]
Nothing specific: once you have Node.js correctly installed locally and after you run `npm install` you should be able to run `npm run build`.
