### ISSUE TITLE
9.2.1: build fails

### ISSUE THREAD

**Issue by kloczek** [nodejs/llhttp#364]
nodejs 20.12.2 and build fails with
```console
+ cd llhttp-9.2.1
+ /usr/bin/make -O -j48 V=1 VERBOSE=1 release TAG=9.2.1 RELEASE=9.2.1
rm -rf release/
rm -rf build/
node_modules/.bin/ts-node bin/generate.ts

/home/tkloczko/rpmbuild/BUILD/llhttp-9.2.1/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/llhttp/constants.ts(331,36): error TS2339: Property 'fromEntries' does not exist on type 'ObjectConstructor'.

    at createTSError (/home/tkloczko/rpmbuild/BUILD/llhttp-9.2.1/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/home/tkloczko/rpmbuild/BUILD/llhttp-9.2.1/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/home/tkloczko/rpmbuild/BUILD/llhttp-9.2.1/node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (/home/tkloczko/rpmbuild/BUILD/llhttp-9.2.1/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Object.require.extensions.<computed> [as .ts] (/home/tkloczko/rpmbuild/BUILD/llhttp-9.2.1/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
make: *** [Makefile:83: generate] Error 1
```

**Comment by kloczek** [comment]
Sorry I just noticed that I've already reported that.
