### ISSUE TITLE
running tests causing clang to abort on double free

### ISSUE THREAD

**Issue by sam-github** [nodejs/llhttp#45]
What version of clang should be used to run the tests?

With x64, ubuntu 19.10, clang 11, I get:

> free(): double free detected in tcache 2

```
core/llhttp (master u=) % git clean -x -d
Removing build/
Removing lib/
Removing node_modules/
Removing tags
Removing test/tmp/
core/llhttp (master u=) % git r
Already up to date.
Current branch master is up to date.
core/llhttp (master u=) % npm i

> llhttp@2.0.4 prepare /home/sam/w/core/llhttp
> npm run clean && npm run build-ts


> llhttp@2.0.4 clean /home/sam/w/core/llhttp
> rm -rf lib && rm -rf test/tmp


> llhttp@2.0.4 build-ts /home/sam/w/core/llhttp
> tsc

added 130 packages from 555 contributors and audited 208 packages in 17.015s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

core/llhttp (master u=) % npm test

> llhttp@2.0.4 test /home/sam/w/core/llhttp
> npm run mocha && npm run lint


> llhttp@2.0.4 mocha /home/sam/w/core/llhttp
> mocha --timeout=10000 -r ts-node/register/type-check --reporter progress test/*-test.ts

warning: overriding the module target triple with x86_64-pc-linux-gnu [-Woverride-module]
free(): double free detected in tcache 2
Stack dump:
0.      Program arguments: /usr/bin/clang -g3 -Os -fvisibility=hidden -I /home/sam/w/core/llhttp/node_modules/llparse-test-fixture/src/native -include /home/sam/w/core/llhttp/test/tmp/http-loose-none.h /home/sam/w/core/llhttp/node_modules/llparse-test-fixture/src/native/fixture.c -msse4.2 -DLLHTTP__TEST -DLLPARSE__ERROR_PAUSE=21 -include /home/sam/w/core/llhttp/test/tmp/cheaders.h /home/sam/w/core/llhttp/test/fixtures/extra.c -DLLHTTP__TEST_HTTP /home/sam/w/core/llhttp/src/native/http.c /home/sam/w/core/llhttp/test/tmp/http-loose-none.bc -o /home/sam/w/core/llhttp/test/tmp/http-loose-none.8804518cbabe475878a3a8a57706e387e22950ed3e9aa6a304e101c771063799
1.      Per-module optimization passes
2.      Running pass 'Dead Argument Elimination' on module '/home/sam/w/core/llhttp/test/tmp/http-loose-none.bc'.
/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamE+0x1f)[0x7fb8ade7c10f]
/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1(_ZN4llvm3sys17RunSignalHandlersEv+0x50)[0x7fb8ade7a3c0]
/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1(_ZN4llvm3sys15CleanupOnSignalEm+0xdd)[0x7fb8ade7b85d]
/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1(+0x8f0c00)[0x7fb8addd0c00]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x15540)[0x7fb8ad4d2540]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7fb8aa8093eb]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7fb8aa7e8899]
/lib/x86_64-linux-gnu/libc.so.6(+0x9038e)[0x7fb8aa85338e]
/lib/x86_64-linux-gnu/libc.so.6(+0x984dc)[0x7fb8aa85b4dc]
/lib/x86_64-linux-gnu/libc.so.6(+0x9a13d)[0x7fb8aa85d13d]
/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1(_ZN4llvm16ValueSymbolTableD2Ev+0x40)[0x7fb8adfca980]
/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1(_ZN4llvm8FunctionD1Ev+0x9a)[0x7fb8adf4f19a]
/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1(_ZN4llvm8Function15eraseFromParentEv+0x58)[0x7fb8adf4bb48]
/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1(_ZN4llvm27DeadArgumentEliminationPass27RemoveDeadStuffFromFunctionEPNS_8FunctionE+0x18bf)[0x7fb8aea7c5cf]
/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1(_ZN4llvm27DeadArgumentEliminationPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE+0xca)[0x7fb8aea7c88a]
/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1(+0x159cba7)[0x7fb8aea7cba7]
/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1(_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE+0x3e0)[0x7fb8adf84820]
/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang17EmitBackendOutputERNS_17DiagnosticsEngineERKNS_19HeaderSearchOptionsERKNS_14CodeGenOptionsERKNS_13TargetOptionsERKNS_11LangOptionsERKN4llvm10DataLayoutEPNSE_6ModuleENS_13BackendActionESt10unique_ptrINSE_17raw_pwrite_streamESt14default_deleteISM_EE+0x31d5)[0x7fb8ac092215]
/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang13CodeGenAction13ExecuteActionEv+0x5fb)[0x7fb8ac31e84b]
/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang14FrontendAction7ExecuteEv+0x48)[0x7fb8ac986518]
/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang16CompilerInstance13ExecuteActionERNS_14FrontendActionE+0x661)[0x7fb8ac93e041]
/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang25ExecuteCompilerInvocationEPNS_16CompilerInstanceE+0x66f)[0x7fb8ac9ea95f]
/usr/bin/clang(_Z8cc1_mainN4llvm8ArrayRefIPKcEES2_Pv+0x989)[0x412179]
/usr/bin/clang[0x410491]
/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11(+0x1980e02)[0x7fb8ac68de02]
/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1(_ZN4llvm20CrashRecoveryContext9RunSafelyENS_12function_refIFvvEEE+0xd7)[0x7fb8addd0a97]
/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZNK5clang6driver10CC1Command7ExecuteEN4llvm8ArrayRefINS2_8OptionalINS2_9StringRefEEEEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPb+0x119)[0x7fb8ac68d339]
/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZNK5clang6driver11Compilation14ExecuteCommandERKNS0_7CommandERPS3_+0x2df)[0x7fb8ac665e4f]
/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZNK5clang6driver11Compilation11ExecuteJobsERKNS0_7JobListERN4llvm15SmallVectorImplISt4pairIiPKNS0_7CommandEEEE+0x7a)[0x7fb8ac665ffa]
/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang6driver6Driver18ExecuteCompilationERNS0_11CompilationERN4llvm15SmallVectorImplISt4pairIiPKNS0_7CommandEEEE+0xdc)[0x7fb8ac678eec]
/usr/bin/clang(main+0x2382)[0x40fd42]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7fb8aa7ea1e3]
/usr/bin/clang(_start+0x2e)[0x40d6fe]
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 11.0.0-++20200207083130+84e5760a163-1~exp1~20200207074603.102
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/fixture-696a01.c
clang: note: diagnostic msg: /tmp/extra-4ab7b2.c
clang: note: diagnostic msg: /tmp/http-57cdd9.c
clang: note: diagnostic msg: /tmp/fixture-696a01.sh
clang: note: diagnostic msg:

********************
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid

/home/sam/w/core/llhttp/node_modules/llparse-test-fixture/src/fixture.ts:233
      throw new Error('clang exit code: ' + (ret.status || ret.signal) +
            ^
Error: clang exit code: SIGABRT
arguments: "-g3" "-Os" "-fvisibility=hidden" "-I" "/home/sam/w/core/llhttp/node_modules/llparse-test-fixture/src/native" "-include" "/home/sam/w/core/llhttp/test/tmp/http-loose-none.h" "/home/sam/w/core/llhttp/node_modules/llparse-test-fixture/src/native/fixture.c" "-msse4.2" "-DLLHTTP__TEST" "-DLLPARSE__ERROR_PAUSE=21" "-include" "/home/sam/w/core/llhttp/test/tmp/cheaders.h" "/home/sam/w/core/llhttp/test/fixtures/extra.c" "-DLLHTTP__TEST_HTTP" "/home/sam/w/core/llhttp/src/native/http.c" "/home/sam/w/core/llhttp/test/tmp/http-loose-none.bc" "-o" "/home/sam/w/core/llhttp/test/tmp/http-loose-none.8804518cbabe475878a3a8a57706e387e22950ed3e9aa6a304e101c771063799"
    at Fixture.clang (/home/sam/w/core/llhttp/node_modules/llparse-test-fixture/src/fixture.ts:233:13)
    at Fixture.build (/home/sam/w/core/llhttp/node_modules/llparse-test-fixture/src/fixture.ts:166:12)
    at Object.build (/home/sam/w/core/llhttp/test/fixtures/index.ts:73:19)
    at buildMode (/home/sam/w/core/llhttp/test/md-test.ts:67:10)
    at Object.<anonymous> (/home/sam/w/core/llhttp/test/md-test.ts:78:13)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Module.m._compile (/home/sam/w/core/llhttp/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Object.require.extensions.<computed> [as .ts] (/home/sam/w/core/llhttp/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /home/sam/w/core/llhttp/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/sam/w/core/llhttp/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/home/sam/w/core/llhttp/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/home/sam/w/core/llhttp/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! llhttp@2.0.4 mocha: `mocha --timeout=10000 -r ts-node/register/type-check --reporter progress test/*-test.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the llhttp@2.0.4 mocha script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sam/.npm/_logs/2020-02-11T18_19_10_563Z-debug.log
npm ERR! Test failed.  See above for more details.
core/llhttp (master u=) %
```

**Comment by indutny** [comment]
I think I should just botch bitcode output. It is causing more problems than it solves (it solves none).

This, for example, looks like a plain clang bug.

**Comment by indutny** [comment]
I'm using:
```
Apple clang version 11.0.0 (clang-1100.0.33.17)
```

and it appears to be compiling alright for me...

**Comment by sam-github** [comment]
Backdated to clang-9, and I can run tests. :tada:  I'm closing this, I'm not sure if I'll upstream a bug report.
